// ─── HERO WODS ───────────────────────────────────────────────────────────────
// Les seances "Hero" du CrossFit portent le nom de militaires, policiers et
// pompiers morts en service. On garde ici la PRESCRIPTION — mouvements, series,
// charges — et une attribution courte et factuelle. Les textes commemoratifs
// appartiennent a leurs auteurs et ne sont pas repris.
//
// Selection : celles realisables avec barre, halteres, kettlebell, machines,
// poulie et poids du corps. Ecartees, celles qui demandent une piscine, un GHD,
// un traineau, une corde a grimper ou un partenaire.
//
// kind    amrap    le plus de tours possible dans le temps imparti
//         fortime  la prescription entiere, le plus vite possible
//         rounds   N tours pour le temps
// cap     minutes ; pour "fortime" c'est un plafond, pas un objectif
// load    charges en kilos, converties des livres et arrondies au disque courant

export const HEROES = [
  // ── Courtes, 10 a 20 minutes ────────────────────────────────────────────────
  { id:"rahoi", name:"Rahoi", kind:"amrap", cap:12, eq:["bar","bw"],
    tribute:"Brian Rahoi, US Army — 2005",
    moves:[{n:"Box jumps",reps:12},{n:"Thrusters",reps:6,kg:43},{n:"Burpees face à la barre",reps:6}] },
  { id:"scotty", name:"Scotty", kind:"amrap", cap:11, eq:["bar","mc","bw"],
    tribute:"Scott Deem, pompier, San Antonio — 2017",
    moves:[{n:"Soulevés de terre",reps:5,kg:102},{n:"Wall-ball",reps:18,kg:9},{n:"Burpees par-dessus la barre",reps:17}] },
  { id:"dg", name:"DG", kind:"amrap", cap:10, eq:["db","bw"],
    tribute:"Daniel Gilbert, US Air Force — 2011",
    moves:[{n:"Toes-to-bar",reps:8},{n:"Thrusters haltères",reps:8,kg:22.5},{n:"Fentes marchées haltères",reps:12,kg:22.5}] },
  { id:"jt", name:"JT", kind:"fortime", cap:20, eq:["bw"], scheme:"21-15-9",
    tribute:"Jeff Taylor, US Navy — 2005",
    moves:[{n:"Handstand push-ups",reps:"21-15-9"},{n:"Dips aux anneaux",reps:"21-15-9"},{n:"Pompes",reps:"21-15-9"}] },
  { id:"dt", name:"DT", kind:"rounds", rounds:5, cap:20, eq:["bar"],
    tribute:"Timothy Davis, US Air Force — 2009",
    moves:[{n:"Soulevés de terre",reps:12,kg:70},{n:"Hang power cleans",reps:9,kg:70},{n:"Push jerks",reps:6,kg:70}] },
  { id:"sham", name:"Sham", kind:"rounds", rounds:7, cap:20, eq:["bar","bw"],
    tribute:"Jeremy Smith, US Air Force — 2011",
    moves:[{n:"Soulevés de terre",reps:11,kg:102},{n:"Sprint 100 m",reps:1}] },
  { id:"coe", name:"Coe", kind:"rounds", rounds:10, cap:25, eq:["bar","bw"],
    tribute:"Michael Coe, US Army — 2007",
    moves:[{n:"Thrusters",reps:10,kg:43},{n:"Pompes aux anneaux",reps:10}] },
  { id:"gator", name:"Gator", kind:"rounds", rounds:8, cap:22, eq:["bar","bw"],
    tribute:"Christopher Blaschum, US Army — 2011",
    moves:[{n:"Front squats",reps:5,kg:84},{n:"Pompes aux anneaux",reps:26}] },
  { id:"wilmot", name:"Wilmot", kind:"rounds", rounds:6, cap:20, eq:["bw"],
    tribute:"Nicholas Wilmot, USMC — 2011",
    moves:[{n:"Squats",reps:50},{n:"Dips aux anneaux",reps:25}] },
  { id:"kutschbach", name:"Kutschbach", kind:"rounds", rounds:7, cap:22, eq:["bar"],
    tribute:"Peter Kutschbach, US Army — 2007",
    moves:[{n:"Back squats",reps:11,kg:84},{n:"Jerks",reps:10,kg:84}] },
  { id:"sean", name:"Sean", kind:"rounds", rounds:10, cap:25, eq:["bar","bw"],
    tribute:"Sean Mullen, pompier, New York — 2011",
    moves:[{n:"Tractions poitrine à la barre",reps:11},{n:"Front squats",reps:22,kg:43}] },
  { id:"tyler", name:"Tyler", kind:"rounds", rounds:5, cap:20, eq:["bar","bw"],
    tribute:"Tyler Parten, US Army — 2009",
    moves:[{n:"Muscle-ups",reps:7},{n:"Sumo deadlift high pull",reps:21,kg:43}] },
  { id:"ryan", name:"Ryan", kind:"rounds", rounds:5, cap:20, eq:["bw"],
    tribute:"Ryan Hummert, pompier, Missouri — 2008",
    moves:[{n:"Muscle-ups",reps:7},{n:"Burpees",reps:21}] },
  { id:"nick", name:"Nick", kind:"rounds", rounds:12, cap:25, eq:["db"],
    tribute:"Nicholas Spehar, US Navy — 2011",
    moves:[{n:"Hang squat cleans haltères",reps:10,kg:20},{n:"Handstand push-ups sur haltères",reps:6}] },
  { id:"erin", name:"Erin", kind:"rounds", rounds:5, cap:22, eq:["db","bw"],
    tribute:"Erin Doyle, US Army — 2008",
    moves:[{n:"Split cleans haltères",reps:15,kg:18},{n:"Tractions",reps:21}] },
  { id:"dork", name:"Dork", kind:"rounds", rounds:6, cap:24, eq:["kb","bw"],
    tribute:"Christopher Campbell, US Army — 2010",
    moves:[{n:"Double-unders",reps:60},{n:"Swings kettlebell",reps:30,kg:24},{n:"Burpees",reps:15}] },
  { id:"k27", name:"K27", kind:"rounds", rounds:27, cap:30, eq:["bar","bw"],
    tribute:"27 opérateurs, opération Red Wings — 2005",
    moves:[{n:"Hang power cleans",reps:5,kg:43},{n:"Burpees",reps:5},{n:"Double-unders",reps:15}] },

  // ── AMRAP de 15 a 30 minutes ────────────────────────────────────────────────
  { id:"jack", name:"Jack", kind:"amrap", cap:20, eq:["bar","kb","bw"],
    tribute:"Jack Booth, US Army — 2010",
    moves:[{n:"Push press",reps:10,kg:52},{n:"Swings kettlebell",reps:10,kg:24},{n:"Box jumps",reps:10}] },
  { id:"jennifer", name:"Jennifer", kind:"amrap", cap:26, eq:["kb","bw"],
    tribute:"Jennifer Sebena, policière, Wisconsin — 2012",
    moves:[{n:"Tractions",reps:10},{n:"Swings kettlebell",reps:15,kg:24},{n:"Box jumps",reps:20}] },
  { id:"tk", name:"TK", kind:"amrap", cap:20, eq:["kb","bw"],
    tribute:"Thomas Kennedy, US Army — 2012",
    moves:[{n:"Tractions strictes",reps:8},{n:"Box jumps",reps:8},{n:"Swings kettlebell",reps:12,kg:24}] },
  { id:"nate", name:"Nate", kind:"amrap", cap:20, eq:["kb","bw"],
    tribute:"Nate Hardy, US Navy — 2008",
    moves:[{n:"Muscle-ups",reps:2},{n:"Handstand push-ups",reps:4},{n:"Swings kettlebell",reps:8,kg:32}] },
  { id:"mcghee", name:"McGhee", kind:"amrap", cap:30, eq:["bar","bw"],
    tribute:"Ryan McGhee, US Army — 2009",
    moves:[{n:"Soulevés de terre",reps:5,kg:125},{n:"Pompes",reps:13},{n:"Box jumps",reps:9}] },
  { id:"danny", name:"Danny", kind:"amrap", cap:20, eq:["bar","bw"],
    tribute:"Daniel Sakai, policier, Oakland — 2009",
    moves:[{n:"Box jumps",reps:30},{n:"Push press",reps:20,kg:52},{n:"Tractions",reps:30}] },
  { id:"artie", name:"Artie", kind:"amrap", cap:20, eq:["bar","bw"],
    tribute:"Arthur Fisher, US Army — 2013",
    moves:[{n:"Tractions",reps:5},{n:"Pompes",reps:10},{n:"Squats",reps:15},{n:"Tractions",reps:5},{n:"Thrusters",reps:10,kg:43}] },
  { id:"rankel", name:"Rankel", kind:"amrap", cap:20, eq:["bar","kb","bw"],
    tribute:"John Rankel, USMC — 2010",
    moves:[{n:"Soulevés de terre",reps:6,kg:102},{n:"Burpee pull-ups",reps:7},{n:"Swings kettlebell",reps:10,kg:24},{n:"Course 200 m",reps:1}] },
  { id:"ledesma", name:"Ledesma", kind:"amrap", cap:20, eq:["mc","bw"],
    tribute:"Ryan Ledesma, policier, Illinois — 2010",
    moves:[{n:"Handstand push-ups sur parallettes",reps:5},{n:"Toes-to-rings",reps:10},{n:"Medicine-ball cleans",reps:15,kg:9}] },
  { id:"ricky", name:"Ricky", kind:"amrap", cap:20, eq:["bar","db","bw"],
    tribute:"Ricky Elliott, pompier, Alaska — 2011",
    moves:[{n:"Tractions",reps:10},{n:"Soulevés de terre haltères",reps:5,kg:32},{n:"Push press",reps:8,kg:52}] },
  { id:"johnson", name:"Johnson", kind:"amrap", cap:20, eq:["bar","bw"],
    tribute:"Michael Johnson, USMC — 2010",
    moves:[{n:"Soulevés de terre",reps:9,kg:111},{n:"Muscle-ups",reps:8},{n:"Squat cleans",reps:9,kg:70}] },
  { id:"marston", name:"Marston", kind:"amrap", cap:20, eq:["bar","bw"],
    tribute:"Daniel Marston, US Army — 2013",
    moves:[{n:"Soulevé de terre",reps:1,kg:184},{n:"Toes-to-bar",reps:10},{n:"Burpees face à la barre",reps:15}] },
  { id:"jbo", name:"JBo", kind:"amrap", cap:28, eq:["bar"],
    tribute:"Jeremy Borden, US Army — 2013",
    moves:[{n:"Overhead squats",reps:9,kg:52},{n:"Développés couchés",reps:12,kg:52}] },
  { id:"zimmerman", name:"Zimmerman", kind:"amrap", cap:25, eq:["bar","bw"],
    tribute:"Kevin Zimmerman, USMC — 2010",
    moves:[{n:"Tractions poitrine à la barre",reps:11},{n:"Soulevés de terre",reps:2,kg:143},{n:"Handstand push-ups",reps:10}] },
  { id:"tom", name:"Tom", kind:"amrap", cap:25, eq:["bar","bw"],
    tribute:"Thomas Kennedy, US Army — 2013",
    moves:[{n:"Muscle-ups",reps:7},{n:"Thrusters",reps:11,kg:70},{n:"Toes-to-bar",reps:14}] },
  { id:"topsy", name:"Topsy", kind:"amrap", cap:25, eq:["bar","mc","bw"],
    tribute:"Michael Topczewski, pompier — 2019",
    moves:[{n:"Muscle-ups aux anneaux",reps:3},{n:"Thrusters",reps:8,kg:43},{n:"Rameur",reps:"17 cal"}] },
  { id:"havana", name:"Havana", kind:"amrap", cap:25, eq:["bar","bw"],
    tribute:"Personnel diplomatique, La Havane — 2017",
    moves:[{n:"Double-unders",reps:150},{n:"Pompes",reps:50},{n:"Power cleans",reps:15,kg:84}] },
  { id:"falkel", name:"Falkel", kind:"amrap", cap:25, eq:["bw"],
    tribute:"Chris Falkel, US Army — 2005",
    moves:[{n:"Handstand push-ups",reps:8},{n:"Box jumps",reps:8},{n:"Montée de corde",reps:1}] },
  { id:"sisson", name:"Sisson", kind:"amrap", cap:20, eq:["bw"],
    tribute:"Michael Sisson, US Army — 2013",
    moves:[{n:"Montée de corde",reps:1},{n:"Burpees",reps:5},{n:"Course 200 m",reps:1}] },
  { id:"buriak", name:"Buriak", kind:"amrap", cap:20, eq:["bar","bw"],
    tribute:"John Buriak, US Army — 2018",
    moves:[{n:"Squat cleans",reps:5,kg:61},{n:"Burpees par-dessus la barre",reps:10},{n:"Tractions",reps:15},{n:"Course 200 m",reps:1}] },
  { id:"harper", name:"Harper", kind:"amrap", cap:23, eq:["bar","bw"],
    tribute:"Bobby Harper, US Army — 2019",
    moves:[{n:"Tractions poitrine à la barre",reps:9},{n:"Power cleans",reps:15,kg:61},{n:"Squats",reps:21},{n:"Course 400 m avec disque",reps:1}] },
  { id:"dunn", name:"Dunn", kind:"amrap", cap:19, eq:["bw"],
    tribute:"Michael Dunn, policier, New York — 2019",
    moves:[{n:"Muscle-ups",reps:3},{n:"Sprint navette",reps:1},{n:"Burpee box jump-overs",reps:6}] },
  { id:"moore", name:"Moore", kind:"amrap", cap:20, eq:["bw"],
    tribute:"Christopher Moore, US Air Force — 2009",
    moves:[{n:"Montée de corde",reps:1},{n:"Course 400 m",reps:1},{n:"Handstand push-ups",reps:"max"}] },

  // ── Pour le temps, 20 a 40 minutes ──────────────────────────────────────────
  { id:"jason", name:"Jason", kind:"fortime", cap:35, eq:["bw"], scheme:"100-75-50-25 squats",
    tribute:"Jason Dahlke, US Navy — 2009",
    moves:[{n:"Squats / Muscle-ups",reps:"100 sq · 5 MU · 75 sq · 10 MU · 50 sq · 15 MU · 25 sq · 20 MU"}] },
  { id:"josh", name:"Josh", kind:"fortime", cap:25, eq:["bar","bw"],
    tribute:"Joshua Hager, US Army — 2007",
    moves:[{n:"Overhead squats",reps:"21-15-9",kg:43},{n:"Tractions",reps:"42-30-18"}] },
  { id:"bell", name:"Bell", kind:"rounds", rounds:3, cap:25, eq:["bar","bw"],
    tribute:"Michael Bell, US Army — 2016",
    moves:[{n:"Soulevés de terre",reps:21,kg:84},{n:"Tractions",reps:15},{n:"Front squats",reps:9,kg:84}] },
  { id:"bradshaw", name:"Bradshaw", kind:"rounds", rounds:10, cap:30, eq:["bar","bw"],
    tribute:"Brian Bradshaw, US Army — 2010",
    moves:[{n:"Handstand push-ups",reps:3},{n:"Soulevés de terre",reps:6,kg:102},{n:"Tractions",reps:12},{n:"Double-unders",reps:24}] },
  { id:"hansen", name:"Hansen", kind:"rounds", rounds:5, cap:35, eq:["kb","bw"],
    tribute:"Daniel Hansen, USMC — 2009",
    moves:[{n:"Swings kettlebell",reps:30,kg:32},{n:"Burpees",reps:30},{n:"Sit-ups",reps:30}] },
  { id:"holleyman", name:"Holleyman", kind:"rounds", rounds:30, cap:35, eq:["bar","mc","bw"],
    tribute:"Aaron Holleyman, US Army — 2004",
    moves:[{n:"Wall-ball",reps:5,kg:9},{n:"Handstand push-ups",reps:3},{n:"Power clean",reps:1,kg:102}] },
  { id:"morrison", name:"Morrison", kind:"fortime", cap:30, eq:["kb","mc","bw"], scheme:"50-40-30-20-10",
    tribute:"Scott Morrison, US Army — 2011",
    moves:[{n:"Wall-ball",reps:"50-40-30-20-10",kg:9},{n:"Box jumps",reps:"50-40-30-20-10"},{n:"Swings kettlebell",reps:"50-40-30-20-10",kg:24}] },
  { id:"wittman", name:"Wittman", kind:"rounds", rounds:7, cap:30, eq:["bar","kb","bw"],
    tribute:"Jeffrey Wittman, policier, Wisconsin — 2010",
    moves:[{n:"Swings kettlebell",reps:15,kg:24},{n:"Power cleans",reps:15,kg:43},{n:"Box jumps",reps:15}] },
  { id:"theseven", name:"The Seven", kind:"rounds", rounds:7, cap:40, eq:["bar","kb","bw"],
    tribute:"Sept agents de la CIA, Camp Chapman — 2009",
    moves:[{n:"Handstand push-ups",reps:7},{n:"Thrusters",reps:7,kg:61},{n:"Knees-to-elbows",reps:7},
           {n:"Soulevés de terre",reps:7,kg:111},{n:"Burpees",reps:7},{n:"Swings kettlebell",reps:7,kg:32},{n:"Tractions",reps:7}] },
  { id:"roy", name:"Roy", kind:"rounds", rounds:5, cap:30, eq:["bar","bw"],
    tribute:"Michael Roy, USMC — 2009",
    moves:[{n:"Soulevés de terre",reps:15,kg:102},{n:"Box jumps",reps:20},{n:"Tractions",reps:25}] },
  { id:"emily", name:"Emily", kind:"rounds", rounds:10, cap:40, eq:["bw"],
    tribute:"Emily Sonnenberg — 2016",
    moves:[{n:"Double-unders",reps:30},{n:"Tractions",reps:15},{n:"Squats",reps:30},{n:"Sprint 100 m",reps:1}] },
  { id:"loredo", name:"Loredo", kind:"rounds", rounds:6, cap:35, eq:["bw"],
    tribute:"Edwardo Loredo, US Army — 2010",
    moves:[{n:"Squats",reps:24},{n:"Pompes",reps:24},{n:"Fentes marchées",reps:24},{n:"Course 400 m",reps:1}] },
  { id:"manion", name:"Manion", kind:"rounds", rounds:7, cap:40, eq:["bar","bw"],
    tribute:"Travis Manion, USMC — 2007",
    moves:[{n:"Course 400 m",reps:1},{n:"Back squats",reps:29,kg:61}] },
  { id:"michael", name:"Michael", kind:"rounds", rounds:3, cap:35, eq:["bw"],
    tribute:"Michael McGreevy, US Navy — 2005",
    moves:[{n:"Course 800 m",reps:1},{n:"Extensions lombaires",reps:50},{n:"Sit-ups",reps:50}] },
  { id:"klepto", name:"Klepto", kind:"rounds", rounds:4, cap:30, eq:["bar","bw"],
    tribute:"Mark Klepacki, US Army — 2010",
    moves:[{n:"Box jumps",reps:27},{n:"Burpees",reps:20},{n:"Squat cleans",reps:11,kg:66}] },
  { id:"ship", name:"Ship", kind:"rounds", rounds:9, cap:30, eq:["bar","bw"],
    tribute:"Marc Small, US Army — 2009",
    moves:[{n:"Squat cleans",reps:7,kg:84},{n:"Burpee box jumps",reps:8}] },
  { id:"holbrook", name:"Holbrook", kind:"rounds", rounds:10, cap:30, eq:["bar","bw"],
    tribute:"Jason Holbrook, US Army — 2010",
    moves:[{n:"Thrusters",reps:5,kg:52},{n:"Tractions",reps:10},{n:"Sprint 100 m",reps:1}] },
  { id:"pheezy", name:"Pheezy", kind:"rounds", rounds:3, cap:30, eq:["bar","bw"],
    tribute:"Mark Forester, US Air Force — 2010",
    moves:[{n:"Front squats",reps:5,kg:75},{n:"Tractions",reps:18},{n:"Soulevés de terre",reps:5,kg:102},
           {n:"Toes-to-bar",reps:18},{n:"Push jerks",reps:5,kg:52},{n:"Pompes relâchées",reps:18}] },
  { id:"marco", name:"Marco", kind:"rounds", rounds:3, cap:25, eq:["bar","bw"],
    tribute:"Marco Silva, pompier, Californie — 2010",
    moves:[{n:"Tractions",reps:21},{n:"Handstand push-ups",reps:15},{n:"Thrusters",reps:9,kg:43}] },
  { id:"randy", name:"Randy", kind:"fortime", cap:15, eq:["bar"],
    tribute:"Randy Simmons, policier, Los Angeles — 2008",
    moves:[{n:"Power snatches",reps:75,kg:34}] },
  { id:"larry", name:"Larry", kind:"fortime", cap:30, eq:["bar","bw"], scheme:"21-18-15-12-9-6-3",
    tribute:"Larry Rougle, US Army — 2007",
    moves:[{n:"Front squats",reps:"21-18-15-12-9-6-3",kg:52},{n:"Burpees face à la barre",reps:"21-18-15-12-9-6-3"}] },
  { id:"donny", name:"Donny", kind:"fortime", cap:25, eq:["bar","bw"], scheme:"21-15-9-9-15-21",
    tribute:"Donald Nichols, US Army — 2010",
    moves:[{n:"Soulevés de terre",reps:"21-15-9-9-15-21",kg:102},{n:"Burpees",reps:"21-15-9-9-15-21"}] },
  { id:"omar", name:"Omar", kind:"fortime", cap:30, eq:["bar","bw"],
    tribute:"Omar Vazquez, US Army — 2011",
    moves:[{n:"Thrusters / Burpees",reps:"10-15-20-25-30-35",kg:43}] },
  { id:"justin", name:"Justin", kind:"fortime", cap:30, eq:["bar","bw"], scheme:"30-20-10",
    tribute:"Justin Wilson, US Army — 2010",
    moves:[{n:"Back squats",reps:"30-20-10",kg:75},{n:"Développés couchés",reps:"30-20-10",kg:75},{n:"Tractions strictes",reps:"30-20-10"}] },
  { id:"alexander", name:"Alexander", kind:"rounds", rounds:5, cap:35, eq:["bar"],
    tribute:"Alexander Povilaitis, US Army — 2012",
    moves:[{n:"Back squats",reps:31,kg:61},{n:"Power cleans",reps:12,kg:84}] },
  { id:"brian", name:"Brian", kind:"rounds", rounds:3, cap:30, eq:["bar","bw"],
    tribute:"Brian Bill, US Navy — 2011",
    moves:[{n:"Montées de corde",reps:5},{n:"Back squats",reps:25,kg:84}] },
  { id:"garrett", name:"Garrett", kind:"rounds", rounds:3, cap:35, eq:["bw"],
    tribute:"Garrett Lawton, USMC — 2008",
    moves:[{n:"Squats",reps:75},{n:"Handstand push-ups aux anneaux",reps:25},{n:"L pull-ups",reps:25}] },
  { id:"ned", name:"Ned", kind:"rounds", rounds:7, cap:40, eq:["bar","mc"],
    tribute:"Edward Byers, US Navy",
    moves:[{n:"Back squats",reps:11,kg:102},{n:"Rameur 1000 m",reps:1}] },

  // ── Les longues, a part ─────────────────────────────────────────────────────
  { id:"murph", name:"Murph", kind:"fortime", cap:60, eq:["bw"], long:true,
    tribute:"Michael Murphy, US Navy — 2005",
    moves:[{n:"Course 1 mile",reps:1},{n:"Tractions",reps:100},{n:"Pompes",reps:200},{n:"Squats",reps:300},{n:"Course 1 mile",reps:1}],
    note:"Fractionnable : 20 tours de 5 tractions, 10 pompes, 15 squats." },
  { id:"tommyv", name:"Tommy V", kind:"fortime", cap:40, eq:["bar","bw"], long:true,
    tribute:"Thomas Valentine, US Army — 2008",
    moves:[{n:"Thrusters",reps:"21-15-9",kg:52},{n:"Montées de corde",reps:"12-9-6"}] },
  { id:"daniel", name:"Daniel", kind:"fortime", cap:35, eq:["bar","bw"], long:true,
    tribute:"Daniel Crabtree, US Army — 2006",
    moves:[{n:"Tractions",reps:50},{n:"Course 400 m",reps:1},{n:"Thrusters",reps:21,kg:43},
           {n:"Course 800 m",reps:1},{n:"Thrusters",reps:21,kg:43},{n:"Course 400 m",reps:1},{n:"Tractions",reps:50}] },
  { id:"hammer", name:"Hammer", kind:"rounds", rounds:5, cap:40, eq:["bar","bw"], long:true,
    tribute:"Nate Hardy et Mike Koch, US Navy — 2008",
    moves:[{n:"Power cleans",reps:5,kg:61},{n:"Front squats",reps:10,kg:61},{n:"Jerks",reps:5,kg:61},{n:"Tractions",reps:20}],
    note:"90 s de repos entre les tours." },
];

// Un Hero doit etre faisable avec le materiel declare. Le poids du corps est
// toujours disponible ; on ne verifie que le reste.
export const heroFits = (h, equipment) => {
  const eq = equipment && equipment.length ? equipment : ["bar","db","kb","mc","cd","bw"];
  return (h.eq || []).every((e) => e === "bw" || eq.indexOf(e) >= 0);
};

export const heroById = (id) => HEROES.find((h) => h.id === id) || null;

// Resume d'une ligne, pour les listes.
export const heroSummary = (h) =>
  h.kind === "amrap" ? `AMRAP ${h.cap} min`
  : h.kind === "rounds" ? `${h.rounds} tours · plafond ${h.cap} min`
  : `Pour le temps · plafond ${h.cap} min`;

// Ce qu'on garde d'une tentative : le temps pour les "for time" et "rounds",
// les tours pour les AMRAP. Deux natures differentes, un seul enregistrement.
export const heroScoreLabel = (h) => (h.kind === "amrap" ? "tours" : "temps");
